site_name: PandasTools
site_url: https://phil65.github.io/PandasTools/
nav:
    - Home: index.md
    - API:
        - dataframe: api/dataframe.md
        - series: api/series.md
        - index: api/index.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme:
    name: material
    custom_dir: docs/theme_customizations/
plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              show_source: true
              inherited_members: false
markdown_extensions:
    # - smarty
    - codehilite
    - admonition
    - pymdownx.superfences
    # - pymdownx.betterem
    # - markdown.extensions.footnotes
    # - markdown.extensions.attr_list
    # - markdown.extensions.def_list
    # - markdown.extensions.tables
    # - markdown.extensions.abbr
    # - markdown.extensions.md_in_html
use_directory_urls: false
